apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-minimal-cluster
  namespace: zalando-postgres
spec:
  teamId: "ACID"
  volume:
    size: 1Gi
    storageClass: standard
  numberOfInstances: 3
  users:
    zalando:  # database owner
    - superuser
    - createdb
    foo_user: []  # role for application foo
  databases:
    foo: zalando  # dbname: owner
    test: zalando
  enableShmVolume: true
  postgresql:
    version: "11"
    parameters:
      shared_buffers: "128MB"
      max_connections: "10"
      log_statement: "all"
      log_destination: "stderr"
      log_directory: "/var/log/postgresql"
  resources:
    requests:
      cpu: 15m
      memory: 150Mi
    limits:
      cpu: 300m
      memory: 275Mi
  patroni:
    initdb:
      encoding: "UTF8"
      locale: "en_US.UTF-8"
      data-checksums: "true"
      auth-host: "scram-sha-256"
    pg_hba:
    - hostssl all all 0.0.0.0/0 scram-sha-256
    - host    all all 0.0.0.0/0 scram-sha-256
    - host    all zalando 192.168.232.109/24 scram-sha-256