# custom api from zalando
# https://github.com/zalando/postgres-operator/tree/master/pkg/apis/acid.zalan.do/v1
apiVersion: "acid.zalan.do/v1"
# custom api object postgresql
# https://github.com/zalando/postgres-operator/blob/master/pkg/apis/acid.zalan.do/v1/postgresql_type.go
kind: postgresql
metadata:
  # name of the pod
  # podtemplate is statefulset -> every instance has the same name with own ordinalindex
  name: postgres-instance
  # namespace in k8s where the pods will be created
  namespace: zalando-postgres
spec:
  dockerImage: registry.opensource.zalan.do/acid/spilo-cdp-12:1.6-p16
  # required parameter from patroni
  teamId: "Postgres"
  # size and accessmode(=defined in storageclass) for persistent volume claim
  volume:
    size: 5Gi
    storageClass: standard
  # number of pods
  # 1 is master, others replicas
  numberOfInstances: 3
  # define some users with access rights
  users:
    zalando:  # database owner
    - superuser
    - createdb
    foo_user: []  # role for application foo
  # define some database with its owner
  databases:
    foo: zalando  # dbname: owner
  # needed for shared_memory, in docker default=64mb 
  enableShmVolume: true
  enableMasterLoadBalancer: true
  enableReplicaLoadBalancer: true
  allowedSourceRanges:  # load balancers' source ranges for both master and replica services
  - 192.168.0.0/16
  postgresql:
    version: "12"
    # parameters for postgresql.conf
    # can be edited after kubectl apply for example and restart spilo service
    parameters:
      listen_addresses: '*'
      shared_buffers: "32MB"
      max_connections: "10"
      log_statement: "all"
      log_destination: "stderr"
      log_directory: "/var/log/postgresql"
  # define the minimum and limit of resources of an postgres database container 
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi
  # parameters for initializing database    
  patroni:
    initdb:
      encoding: "UTF8"
      locale: "en_US.UTF-8"
      data-checksums: "true"
      auth-host: "scram-sha-256"
    # entries for host-based access file in postgres  
    pg_hba:
    - hostssl all all 0.0.0.0/0 scram-sha-256
    - host    all all 0.0.0.0/0 scram-sha-256