filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
filebeat.modules:
- module: postgresql
filebeat.inputs:
- type: docker
  containers.ids:
  - '*'
  processors:
  - add_kubernetes_metadata:
      in_cluster: true

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}'
setup.kibana:
  host: 'efk-kibana:30126'
